language: java

jdk:
   - openjdk7
   - oraclejdk7
   - openjdk6
   - oraclejdk8

after_success:
   - mvn clean cobertura:cobertura
   - mvn test

#jdk:
#  - oraclejdk8
#  - oraclejdk7
#  - openjdk6
#after_success:
#  - mvn clean test jacoco:report #coveralls:report -DrepoToken=$COVERALLS_ID